### ISSUE TITLE
Execute code on releaseContext

### ISSUE THREAD

**Issue by gpulido** [Ekito/koin#64] opened 2018-02-27 08:43 UTC
Hello,
I'm trying to use Koin with MVVM (android components) and Realm.

Realm forces a get an instance that has to be released to maintain the reference count.

I'm trying to figure out how to adquire koin in my scenario.

I have the following structure (simplified for the sake of the example)
```Kotlin

class ArchersViewModel: ViewModel()
{

 val mDb: Realm

    val viewModelDao
    init {
        mDb = Realm.getDefaultInstance()
        viewModelDao = ArcherDao(mDb)
    }
    override fun onCleared() {
        mDb.close()
        super.onCleared()
    }
}

class ArcherDao(realm: Realm): RealmObjectDao<Archer>(realm, Archer::class.java)
{
  //methods to retrieve data
}


class ArchersFragment:Fragment()
{
lateinit var realmObjectListViewModel: ArchersViewModel
  override fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)
        realmObjectListViewModel = ViewModelProviders.of(this).get(ArchersViewModel::class.java)

}
```

So to start using koin I adapt the classes to use a koin module:
 ```kotlin

val archersModule = applicationContext {
    context("ArcherContext")
    {
        viewModel { ArchersViewModel(get())}
        bean { ArcherDao(get()) }
        provide { Realm.getDefaultInstance() as Realm}
    }
}

```
So I can modify the classes:

```kotlin
class ArchersViewModel(val viewModelDao: ArcherDao)
{
 ....
}
class ArcherDao(realm: Realm): RealmObjectDao<Archer>(realm, Archer::class.java)
{
  //methods to retrieve data
}
class ArchersFragment:Fragment()
{
    val realmObjectListViewModel by viewModel<ArchersViewModel>()

}

```
But now I have two doubts:
1) Where I should release the context and
2) How to force to close the realm instance when release the context

Any suggestion?

Thank in advance
Regards

**Comment by arnaudgiuliani** [comment] 2018-02-27 14:42
Hello,

For your question `1.` : the `releaseContext()` function is entirely agnostic. It allows being used when you really need it. on ViewModel lifecycle, one easy way to drop any instances would be on the `onClear()` from ViewModel. From this point, you know that all will be released and your view is being dropped.
For such usage, add the `KoinComponent` to your ViewModel class, else you won't be able to run the `releaseContext` function.

for your `2nd` point: the context release will drop all instances from the context and child contexts. This mean that Koin will drop `ArcherDao` and `Realm` instances as soon as you call the `releaseContext`. Next time you will ask for those components, Koin will recreate new instances.
 
Do you have to call a special API on `Realm` drop?

To process components lifecycle, we have 2 ways:

* Use `factory` instead of `bean` or `provide` to provide a factory definition - the problem is that you will have a new instance each time you ask for this component
* Use a `context` (as you've already done), to gather definitions of components to be dropped in some lifecycle. The idea is that you have to share instances for an amount of time, before dropping them.

You can write an abstract `ViewModel` class to embed `releaseContext` behavior.

**Comment by gpulido** [comment] 2018-02-27 15:35
Hello again,
Thank you very much for your detail explanation.

I already have a base viewmodel that will be the one to release the context by name, I just tried to simplify the example, at this moment all my viewmodels are dependant class from 
```Kotlin
abstract class RealmViewModel: ViewModel()
{

    val mDb: Realm

    init {
        mDb = Realm.getDefaultInstance()
    }


    override fun onCleared() {
        mDb.close()
        super.onCleared()
    }

}
```
What I would do is change that class by something like:
```Kotlin
abstract class ContextAwareViewModel(): ViewModel(), KoinComponent
{   
   abstract fun getContextName():String
    override fun onCleared() {
        releaseContext(getContextName())
        super.onCleared()
    }
}
```
Refarding realm, it is mandatory that for each "mdb = Realm.getDefaultInstance()" call a "mdb.close()" call  has to be made.
So it is not enough to "release" the instance, an specific call must be made.
How can I do it on the releasecontext?

Regards
Gabriel

**Comment by arnaudgiuliani** [comment] 2018-02-28 09:50
There is no hook system on `releaseContext`. You have to write your own component that will call the `releaseContext()` and your `mDb.close()`. Koin gives the function to call it. You make your own component hierarchy/lifecycle. 

Your `ContextAwareViewModel` should extend `RealmViewModel`, or you should write a mix of those 2 classes. 

Question: does the `Realm.getDefaultInstance()` give you a new instance each time?

**Comment by gpulido** [comment] 2018-02-28 10:22
Hello,
I agree with you, and I already realized that. 
Also I'm reviewing the realm code, and it seems that I could just use the same realm instance created at application level (and in this case the applicationcontext would suffice) and release it with the application.
My error was to try to directly use the same structures adding just a di framework but as the di framework ensures me that the realm instance is called just one and is on the needed thread, I could just try to use the injected realm at an application level.

However, I think it would be nice to have some kind of hook when the instances are released by the context to just allow to do some cleaning if needed.

Now I'm trying to figure out the best way to pass the property id on details viewmodels as I'm using simple-stack to handle the navigation.

**Comment by arnaudgiuliani** [comment] 2018-02-28 13:53
For last release, I've just added a context callback interface, to be notified on context release.
Just call the `registerContextCallBack()` function to register it

You will be also able to use parameters to viewModel like: `viewmModel{ params -> MyViewModel(params["id"])}`

and provide "id" parameter with :  `val myVM : MyViewModel by inject( parameters = mapOf("id" to id))`

**Comment by gpulido** [comment] 2018-02-28 14:04
That is awesome!!
Just a question regarding the vierwmodel params, before koin I used a viewmodel factory that would add the parameters on the build of the viewmodel, so if the factory was called with two differents id, two different viewmodel instances were being created.
With the new implementation (0.9.0) will be behave the same way? if not I need to figure out how to inject two different vm instances of the same class.
(When the 0.9.0 version will be released  ? )
Thanks!

**Comment by arnaudgiuliani** [comment] 2018-02-28 14:41
Yes exactly, it will run like your old viewmodel factory. I'm currently finalizing the feature.

`0.9.0` will be released end of this week or next week.

**Comment by fredy-mederos** [comment] 2018-02-28 15:47
I have a question about viewModels with params:
If I want to share a viewModel between an activity and its fragments but the param is only known in the activity (because it is an intent extra). am I able to reuse it even when the injection is different??

In my activity:
```kotlin
val myVM : MyViewModel by inject( parameters = mapOf("id" to id))
```

in my Fragments:
```kotlin
val myVM : MyViewModel by inject()
```

**Comment by gpulido** [comment] 2018-02-28 16:19
Hello,
I guess that it would behave the same way as in the "viewmodel factory" pattern. They will be two different viewmodels instances. 
You will need to pass the id parameter to the fragment somehow, so it can ask for the vm properly.
Again, If I'm right, the parameters are just "constructor" parameters, so if you are calling the di using two different constructors (one with parameter id and one without parameter) they will be different, and also you will need two constructors.
Imagine that in the activity you want two instances of the vm with different parameters:
```Kotlin
val myVM : MyViewModel by inject( parameters = mapOf("id" to id))
val myVM2 : MyViewModel by inject( parameters = mapOf("id2" to id))
```
That is an acceptable scenario. When the fragment ask for the viewmodel which one has to be returned?

So, at the end what do you need is a mechanism to share the id between the activity and the fragment.

**Comment by fredy-mederos** [comment] 2018-02-28 16:50
I can share the id with fragments using `Fragment().withArguments(....)` and take them in fragments via arguments. 
Hum… this way I'll need to write a lot more than just using id as a var and initializing it in my activity onCreate() :p

To get different viewModels instances I can use the “name” argument. So If I don’t provide any name then all shared viewModels should be the same, right?

If we just use a different dataStructure to store parameters in the viewModels KoinFactory ??
If we distinct the viewModels parameters by class name and provided name??
It will look like this:
`internal val parameters: Map<String,ParameterMap>`

What do you think??

**Comment by arnaudgiuliani** [comment] 2018-03-01 09:16
The `by viewModel()` and `getViewModel()` functions will be able to have a `key` (ViewModelFactory instance key) and a `name` (Koin beande finition name).

**Comment by arnaudgiuliani** [comment] 2018-03-01 10:41
I close the issue

**Closed by arnaudgiuliani** 2018-03-01 10:41 UTC
Labels: enhancement
